language: cpp
sudo: required
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libglew-dev
            - libsdl2-dev 
            - libsdl2-image-dev
            - libgtest-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
    - eval "${MATRIX_EVAL}"
    - echo Install GTest
    - sudo mkdir /usr/src/gtest/build
    - sudo chmod -R 777 /usr/src/gtest/build
    - cd /usr/src/gtest/build
    - cmake ..
    - make
    - sudo cp /usr/src/gtest/build/libgtest* /usr/local/lib/
    - cd -
script: 
    - echo Build MagicCube
    - mkdir build && cd build
    - cmake .. && make
    - ./bin/MagicCube_client_test
